# TASK-1

Develop a function that takes the following input:
- **String**: `planet`
- **Float**: `weight in pounds` - The weight of an object on Earth.

The function should return:
- **Float**: The weight of the object in kilograms on the specified planet.

### Weight Multipliers:
- **Sun**: Weight on Earth × 27.01  
- **Mercury**: Weight on Earth × 0.38  
- **Venus**: Weight on Earth × 0.91  
- **Moon**: Weight on Earth × 0.166  
- **Mars**: Weight on Earth × 0.38  
- **Jupiter**: Weight on Earth × 2.34  
- **Saturn**: Weight on Earth × 1.06  
- **Uranus**: Weight on Earth × 0.92  
- **Neptune**: Weight on Earth × 1.19  
- **Pluto**: Weight on Earth × 0.6  

### Additional Requirements:
- Display at least **3 test cases** with various arguments to validate the implementation.

In [5]:
"""
Answer to TASK-1. 
Author: Viswanath S Chirravuri / viswanath.chirravuri@gwu.edu

Calculate the weight of an object in kilograms on a specified star in the solar system.
    Accepted Parameters are:
        planet (str): The name of the star.
        weight_pounds (float): The weight of the object on Earth in pounds.

    It returns:
        float: The weight of the object on the specified star in the solar system in kilograms.
"""
import logging

# Configure logging
logging.basicConfig(level=logging.ERROR, format='%(asctime)s - %(levelname)s - %(message)s')

"""
Calculate weight on a celestial body based on its gravitational multiplier.

Args:
    planet (str): Name of the celestial body.
    weight_pounds (float): Weight in pounds on Earth.

Returns:
    float: Equivalent weight in kilograms on the specified celestial body.

Raises:
    ValueError: If inputs are invalid or planet data is unavailable.
"""
def weight_on_star(planet: str, weight_pounds: float) -> float:

    # Define a dictionary with weight multipliers for celestial bodies
    STAR_WEIGHT_MULTIPLIERS = {
        "Sun": 27.01,
        "Mercury": 0.38,
        "Venus": 0.91,
        "Moon": 0.166,
        "Mars": 0.38,
        "Jupiter": 2.34,
        "Saturn": 1.06,
        "Uranus": 0.92,
        "Neptune": 1.19,
        "Pluto": 0.6,
    }

    # Input validation
    if not isinstance(planet, str):
        logging.error("Invalid input: planet must be a string.")
        raise ValueError("Planet name must be a string.")
    
    if not isinstance(weight_pounds, (int, float)) or weight_pounds <= 0:
        logging.error("Invalid input: weight must be a positive number.")
        raise ValueError("Weight must be a positive number.")
    
    # Check if the planet exists in the dictionary
    if planet not in STAR_WEIGHT_MULTIPLIERS:
        logging.error(f"Data for planet '{planet}' not available.")
        raise ValueError(f"Data for planet '{planet}' is not available.")
    
    # Convert weight from pounds to kilograms (1 pound = 0.453592 kg)
    weight_kg_on_earth = weight_pounds * 0.453592
    
    # Calculate the weight on the specified celestial body
    weight_kg_on_star = weight_kg_on_earth * STAR_WEIGHT_MULTIPLIERS[planet]
    
    return weight_kg_on_star

# Test cases
def main():
    test_cases = [
        ("Mars", 150),
        ("Jupiter", 200),
        ("Moon", 100),
        ("Galaxy", 75),  # Invalid test case
        ("Sun", 50),
    ]

    for planet, weight in test_cases:
        try:
            result = weight_on_star(planet, weight)
            print(f"Weight of {weight} pounds on Earth is approximately {result:.2f} kg on {planet}.")
        except ValueError as e:
            print(e)

if __name__ == "__main__":
    main()

2024-11-20 17:36:14,955 - ERROR - Data for planet 'Galaxy' not available.

Weight of 150 pounds on Earth is approximately 25.85 kg on Mars.
Weight of 200 pounds on Earth is approximately 212.28 kg on Jupiter.
Weight of 100 pounds on Earth is approximately 7.53 kg on Moon.
Data for planet 'Galaxy' is not available.
Weight of 50 pounds on Earth is approximately 612.58 kg on Sun.

# TASK-2

Create a class and objects as described: 

### **Class Definition:**
- Create a class called Product with the following attributes:
    - **name**: The name of the product (string).
    - **price**: The price of the product (float).
    - **quantity**: The quantity of the product in stock (integer).
- The class should also have the following methods:
    - **\_\_init\_\_(self, name, price, quantity)**: A constructor that initializes the attributes.
    - **restock(self, amount)**: This method should increase the quantity of the product by the given amount.
    - **sell(self, amount)**: This method should decrease the quantity by the given amount if there is enough stock. If not, it should print a message indicating insufficient stock.
    - **\_\_str\_\_(self)**: This method should return a string representation of the product, including its name, price, and quantity.

### **Creating Objects:**
- Create three different product objects using the Product class:
    - **Product 1**: "Laptop", priced at \$1200, with a quantity of 10.
    - **Product 2**: "Smartphone", priced at \$800, with a quantity of 25.
    - **Product 3**: "Headphones", priced at \$150, with a quantity of 50.

### **Interacting with Objects:**
- Perform the following operations:
    - Print the details of each product.
    - Sell 3 units of the "Laptop" and 5 units of the "Smartphone".
    - Restock the "Headphones" with an additional 30 units.
    - Print the details of each product again after the above operations.

In [13]:
'''
Answer to TASK-2. 
Author: Viswanath S Chirravuri / viswanath.chirravuri@gwu.edu
'''
import logging

# Configure logging to track errors and information
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

#creating a new class called Product
class Product:
    """
    Initializes the product with a name, price, and stock quantity.
    
    Args:
        product_name (str): The name of the product.
        unit_price (float): The price of the product.
        stock_quantity (int): The quantity of the product in stock.
    """
    def __init__(self, product_name: str, unit_price: float, stock_quantity: int):
        self._product_name = product_name
        self._unit_price = unit_price
        self._stock_quantity = stock_quantity

    # Getter methods to access private variables
    @property
    def product_name(self):
        return self._product_name

    @property
    def unit_price(self):
        return self._unit_price

    @property
    def stock_quantity(self):
        return self._stock_quantity

    # Method to restock the product, increasing the quantity by a certain amount
    def restock(self, quantity: int):
        if quantity <= 0:
            logging.error(f"Invalid restock quantity: {quantity}. Quantity must be positive.")
            raise ValueError("Restock quantity must be positive.")
        self._stock_quantity += quantity
        logging.info(f"Restocked {quantity} units of {self._product_name}. New stock: {self._stock_quantity}")
        print(f"Restocked {quantity} units of {self._product_name}. New stock: {self._stock_quantity}")

    # Method to sell the product, decreasing the quantity if there is enough stock
    def sell(self, quantity: int):
        if quantity <= 0:
            logging.error(f"Invalid sell quantity: {quantity}. Quantity must be positive.")
            raise ValueError("Sell quantity must be positive.")
        if quantity > self._stock_quantity:
            logging.warning(f"Insufficient stock to sell {quantity} units of {self._product_name}. Available: {self._stock_quantity}")
            raise ValueError("Not enough stock available.")
        self._stock_quantity -= quantity
        logging.info(f"Sold {quantity} units of {self._product_name}. Remaining stock: {self._stock_quantity}")
        print(f"Sold {quantity} units of {self._product_name}. Remaining stock: {self._stock_quantity}")

    # Method to return a formatted string representation of the product
    def __str__(self):
        return f"Product: {self._product_name}, Price: ${self._unit_price:.2f}, Quantity: {self._stock_quantity}"

# Creating products as part of the inventory
laptop = Product("Laptop", 1200, 10)
smartphone = Product("Smartphone", 800, 25)
headphones = Product("Headphones", 150, 50)

# Print initial details of each product
print(f"Initial Product Details:\n{laptop}\n{smartphone}\n{headphones}")

# Perform transactions and print the result to the screen
try:
    laptop.sell(3)  # Sell 3 units of "Laptop"
    smartphone.sell(5)  # Sell 5 units of "Smartphone"
    headphones.restock(30)  # Restock "Headphones" with 30 more units
except ValueError as e:
    logging.error(f"Error in transaction: {e}")
    print(f"Error: {e}")

# Print updated details of each product
print("\nAfter transactions:")
print(laptop)
print(smartphone)
print(headphones)

Initial Product Details:
Product: Laptop, Price: $1200.00, Quantity: 10
Product: Smartphone, Price: $800.00, Quantity: 25
Product: Headphones, Price: $150.00, Quantity: 50
Sold 3 units of Laptop. Remaining stock: 7
Sold 5 units of Smartphone. Remaining stock: 20
Restocked 30 units of Headphones. New stock: 80

After transactions:
Product: Laptop, Price: $1200.00, Quantity: 7
Product: Smartphone, Price: $800.00, Quantity: 20
Product: Headphones, Price: $150.00, Quantity: 80

# TASK-3

## Load the data
Load the **auto.csv** file from Electronic Reserves as a data frame called ***df_auto_1***

### Verify the data
Display the first 20 records of the data frame.

### Research pandas documentation
Explore documentation and find a pandas method that would display the column names (a.k.a. axis 1) of the data frame. 

### Print and Play with data
- Display the column names.
- Identify and deal with by dropping a row (axis 0) where any missing data is found (NaN)
- Hint:  explore the pandas ***Dataframe.dropna()*** library method.  
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

In [15]:
'''
Answer to TASK-3. 
Author: Viswanath S Chirravuri / viswanath.chirravuri@gwu.edu
'''
import pandas as pd
import os

# Not using the below code to load google's library for drive as my notebook is on local anaconda setup and my CSV file is in same path as ipynb file
# from google.colab import drive and drive.mount('/content/drive') 

# Check if the file 'auto.csv' exists before attempting to read it
csv_file = 'auto.csv'
if not os.path.exists(csv_file):
    print(f"Error: The file '{csv_file}' does not exist in the current directory.")
else:
    try:
        # Load the auto.csv file as a DataFrame
        df_auto_1 = pd.read_csv(csv_file)  # Read the CSV file into a DataFrame

        # Display the first 20 records of the DataFrame
        print("First 20 records of the DataFrame:")
        print(df_auto_1.head(20))  # Display the first 20 rows of the DataFrame

        # Display the column names (axis 1 refers to columns)
        print("\nColumn names of the DataFrame:")
        print(df_auto_1.columns)  # Print the column names

        # Check for missing data (NaN) in the DataFrame
        missing_data_count = df_auto_1.isna().sum().sum()  # Count the total number of NaN values in the DataFrame
        if missing_data_count > 0:
            print(f"\nWarning: There are {missing_data_count} missing values in the DataFrame.")
        else:
            print("\nNo missing values in the DataFrame.")

        # Drop rows where any missing data (NaN) is found
        df_auto_1_cleaned = df_auto_1.dropna(axis=0)  # Drop rows with any NaN values

        # Display the cleaned DataFrame (without rows containing NaN)
        print("\nDataFrame after dropping rows with NaN values:")
        print(df_auto_1_cleaned)  # Display the cleaned DataFrame
    except Exception as e:
        print(f"An error occurred while processing the CSV file: {e}")

First 20 records of the DataFrame:
     mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0   18.0          8         307.0        130    3504          12.0    70
1   15.0          8         350.0        165    3693          11.5    70
2   18.0          8         318.0        150    3436          11.0    70
3   16.0          8         304.0        150    3433          12.0    70
4   17.0          8         302.0        140    3449          10.5    70
5   15.0          8         429.0        198    4341          10.0    70
6   14.0          8         454.0        220    4354           9.0    70
7   14.0          8         440.0        215    4312           8.5    70
8   14.0          8         455.0        225    4425          10.0    70
9   15.0          8         390.0        190    3850           8.5    70
10  15.0          8         383.0        170    3563          10.0    70
11  14.0          8         340.0        160    3609           8.0    70
12  15.0          8         400.0        150    3761           9.5    70
13  14.0          8         455.0        225    3086          10.0    70
14  24.0          4         113.0         95    2372          15.0    70
15  22.0          6         198.0         95    2833          15.5    70
16  18.0          6         199.0         97    2774          15.5    70
17  21.0          6         200.0         85    2587          16.0    70
18  27.0          4          97.0         88    2130          14.5    70
19  26.0          4          97.0         46    1835          20.5    70

    origin                          name
0        1     chevrolet chevelle malibu
1        1             buick skylark 320
2        1            plymouth satellite
3        1                 amc rebel sst
4        1                   ford torino
5        1              ford galaxie 500
6        1              chevrolet impala
7        1             plymouth fury iii
8        1              pontiac catalina
9        1            amc ambassador dpl
10       1           dodge challenger se
11       1            plymouth 'cuda 340
12       1         chevrolet monte carlo
13       1       buick estate wagon (sw)
14       3         toyota corona mark ii
15       1               plymouth duster
16       1                    amc hornet
17       1                 ford maverick
18       3                  datsun pl510
19       2  volkswagen 1131 deluxe sedan

Column names of the DataFrame:
Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

No missing values in the DataFrame.

DataFrame after dropping rows with NaN values:
      mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70
1    15.0          8         350.0        165    3693          11.5    70
2    18.0          8         318.0        150    3436          11.0    70
3    16.0          8         304.0        150    3433          12.0    70
4    17.0          8         302.0        140    3449          10.5    70
..    ...        ...           ...        ...     ...           ...   ...
392  27.0          4         140.0         86    2790          15.6    82
393  44.0          4          97.0         52    2130          24.6    82
394  32.0          4         135.0         84    2295          11.6    82
395  28.0          4         120.0         79    2625          18.6    82
396  31.0          4         119.0         82    2720          19.4    82

     origin                       name
0         1  chevrolet chevelle malibu
1         1          buick skylark 320
2         1         plymouth satellite
3         1              amc rebel sst
4         1                ford torino
..      ...                        ...
392       1            ford mustang gl
393       2                  vw pickup
394       1              dodge rampage
395       1                ford ranger
396       1                 chevy s-10

[397 rows x 9 columns]

# TASK-4

What is the mean AND standard deviation of the column cylinders?  Also, use a method to display basic descriptive statistics of all columns.  Show code and answer.

In [17]:
'''
Answer to TASK-4. 
Author: Viswanath S Chirravuri / viswanath.chirravuri@gwu.edu
'''
import pandas as pd
import os

# Define the file path
csv_file = 'auto.csv'

# Check if the file exists before trying to read it
if not os.path.exists(csv_file):
    print(f"Error: The file '{csv_file}' does not exist in the current directory.")
else:
    try:
        # Load the 'auto.csv' file into a DataFrame
        df_auto_1 = pd.read_csv(csv_file)

        # Check if 'cylinders' column exists in the DataFrame
        if 'cylinders' not in df_auto_1.columns:
            print("Error: The 'cylinders' column is missing from the CSV file.")
        else:
            # Calculate the mean of the 'cylinders' column
            mean_cylinders = df_auto_1['cylinders'].mean()

            # Calculate the standard deviation of the 'cylinders' column
            std_cylinders = df_auto_1['cylinders'].std()

            # Display basic descriptive statistics for all columns
            descriptive_stats = df_auto_1.describe()

            # Output the results
            print(f"Mean of 'cylinders' column: {mean_cylinders}")
            print(f"Standard Deviation of 'cylinders' column: {std_cylinders}")
            print("\nBasic Descriptive Statistics for All Columns:")
            print(descriptive_stats)

    except Exception as e:
        # Catch any other errors (e.g., file reading issues, wrong data format, etc.)
        print(f"An error occurred: {e}")

Mean of 'cylinders' column: 5.458438287153652
Standard Deviation of 'cylinders' column: 1.7015769807918517

Basic Descriptive Statistics for All Columns:
              mpg   cylinders  displacement       weight  acceleration  \
count  397.000000  397.000000    397.000000   397.000000    397.000000
mean    23.515869    5.458438    193.532746  2970.261965     15.555668
std      7.825804    1.701577    104.379583   847.904119      2.749995
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    104.000000  2223.000000     13.800000
50%     23.000000    4.000000    146.000000  2800.000000     15.500000
75%     29.000000    8.000000    262.000000  3609.000000     17.100000
max     46.600000    8.000000    455.000000  5140.000000     24.800000

             year      origin
count  397.000000  397.000000
mean    75.994962    1.574307
std      3.690005    0.802549
min     70.000000    1.000000
25%     73.000000    1.000000
50%     76.000000    1.000000
75%     79.000000    2.000000
max     82.000000    3.000000

# TASK-5

- Use iloc to create a new dataframe called ***df\_auto\_2*** of the 10th through but not including the 20th row and the 2nd though last column.
    - Display results.

### Reference Information

- Hint: iloc returns rows and columns that meet a condition based on index location \[start_row:end_row, start_column:end_column].
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc
- For example:  df2 = df1.iloc\[0:20, 3:] provides rows 0-19 and the 3rd through last columns of a dataset.

In [1]:
'''
Answer to TASK-5. 
Author: Viswanath S Chirravuri / viswanath.chirravuri@gwu.edu
'''
import pandas as pd
import os

# Define the file path
csv_file = 'auto.csv'

# Check if the file exists before trying to read it
if not os.path.exists(csv_file):
    print(f"Error: The file '{csv_file}' does not exist in the current directory.")
else:
    try:
        # Load the 'auto.csv' file into a DataFrame
        df_auto_1 = pd.read_csv(csv_file)

        # Check if the DataFrame has enough rows and columns for the operation
        if df_auto_1.shape[0] < 20:  # Ensure there are at least 20 rows
            print("Error: The DataFrame does not have enough rows for this operation.")
        elif df_auto_1.shape[1] < 2:  # Ensure there are at least 2 columns
            print("Error: The DataFrame does not have enough columns for this operation.")
        else:
            # Use iloc to select the 10th through 19th rows (index 9 to 19)
            # and the 2nd through last columns (index 1 to last column)
            df_auto_2 = df_auto_1.iloc[9:19, 1:]

            # Display the new DataFrame
            print("Selected rows and columns from the DataFrame:")
            print(df_auto_2)  # Print the subset of the DataFrame
    except Exception as e:
        # Catch any errors that occur during file reading or data manipulation
        print(f"An error occurred: {e}")

Selected rows and columns from the DataFrame:
    cylinders  displacement horsepower  weight  acceleration  year  origin  \
9           8         390.0        190    3850           8.5    70       1
10          8         383.0        170    3563          10.0    70       1
11          8         340.0        160    3609           8.0    70       1
12          8         400.0        150    3761           9.5    70       1
13          8         455.0        225    3086          10.0    70       1
14          4         113.0         95    2372          15.0    70       3
15          6         198.0         95    2833          15.5    70       1
16          6         199.0         97    2774          15.5    70       1
17          6         200.0         85    2587          16.0    70       1
18          4          97.0         88    2130          14.5    70       3

                       name
9        amc ambassador dpl
10      dodge challenger se
11       plymouth 'cuda 340
12    chevrolet monte carlo
13  buick estate wagon (sw)
14    toyota corona mark ii
15          plymouth duster
16               amc hornet
17            ford maverick
18             datsun pl510

# TASK-6

### Input the following code and execute loc requirement below:
```python
employees = {
    'EmployeeID': [1, 2, 3, 4, 5],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'DepartmentID': [101, 102, 101, 103, 102]
df_employees = pd.DataFrame(employees)
df_departments = pd.DataFrame(departments)
```

### Requirement details
Using loc, find out which employees belong to the department ‘101’.

### Hints
- Hint:  loc returns data based on searching for a value in a pandas dataframe.
- Example: To create a new dataframe called result from original dataframe called df where “hello” is a value in the column called “greeting”.
- Answer: result = df.loc\[df\['greeting'] == 'hello']

In [21]:
'''
Answer to TASK-6. 
Author: Viswanath S Chirravuri / viswanath.chirravuri@gwu.edu
'''
import pandas as pd  # Import pandas library

# Define the employees dictionary with employee data
employees = {
    'EmployeeID': [1, 2, 3, 4, 5],  # Employee IDs
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],  # Employee names
    'DepartmentID': [101, 102, 101, 103, 102]  # Department IDs each employee belongs to
}

# Function to safely create a DataFrame from a dictionary
def create_dataframe(data_dict):
    try:
        # Check if required keys are present in the dictionary
        required_keys = ['EmployeeID', 'Employee', 'DepartmentID']
        for key in required_keys:
            if key not in data_dict:
                raise KeyError(f"Missing required key: {key}")
        
        # Create DataFrame from the provided dictionary
        df = pd.DataFrame(data_dict)
        return df
    
    except KeyError as e:
        print(f"Error: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred while creating the DataFrame: {e}")
        return None

# Create DataFrame from employees dictionary
df_employees = create_dataframe(employees)  # Convert the dictionary to a DataFrame

# Check if the DataFrame was created successfully
if df_employees is not None:
    try:
        # Ensure the 'DepartmentID' column exists before trying to filter it
        if 'DepartmentID' not in df_employees.columns:
            raise ValueError("The 'DepartmentID' column is missing in the DataFrame.")
        
        # Use loc to find employees in department 101
        result = df_employees.loc[df_employees['DepartmentID'] == 101]  # Filter rows where the department is 101
        
        # Display the result DataFrame
        print("Employees in Department 101:")
        print(result)  # Output the rows of employees who belong to department 101
    
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An error occurred while processing the DataFrame: {e}")
else:
    print("Failed to create the DataFrame. Please check the input data.")

Employees in Department 101:
   EmployeeID Employee  DepartmentID
0           1    Alice           101
2           3  Charlie           101